steps:
  # Membuat image Docker dengan nama note-backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/note-backend", "."]

  # Push image ke Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/note-backend"]

  # Deploy ke Cloud Run dengan nama service note-backend
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "note-backend",
        "--image",
        "gcr.io/$PROJECT_ID/note-backend",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya disimpan di Google Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
